- name: install packages
  apt:
          pkg:
          - vim
          - htop
          - net-tools
          - iftop
          - man
          - ntp
          - apt-transport-https
          - less
          - screen
          - netcat-openbsd
          - curl
          - wget
          - git
          - ca-certificates
          - acl
          - ufw

# fw default deny incoming
# ufw default allow outgoing
# sudo ufw allow 22
# ufw enable

