- name: install dehydrated for letsencrypt host verification
  apt:
    pkg:
    - dehydrated
    - dehydrated-apache2
    update_cache: yes
- template:
    src: templates/domains.j2
    dest: /etc/dehydrated/domains.txt
- command: cp /usr/share/doc/dehydrated/examples/hook.sh /etc/dehydrated/hook.sh
- template:
    src: templates/contact.j2
    dest: /etc/dehydrated/conf.d/contact.sh
- copy:
    src: files/hook.sh
    dest: /etc/dehydrated/hook.sh
- command: dehydrated --register --accept-terms
- command: dehydrated -c
- template:
    src: templates/apache_conf_post_ssl.j2
    dest: /etc/apache2/sites-available/{{host}}.{{domain}}.conf
- command: a2enmod ssl
- service:
    name: apache2
    state: reloaded
- copy:
    src: files/dehydrated_cronjob
    dest: /etc/cron.weekly/dehydrated
